version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=AppDb;User=sa;Password=Your_strong_password123;TrustServerCertificate=True;
      - Jwt__Key=supersecretkeythatisatleast32characterslong
      - Jwt__Issuer=server-dotnet
      - Jwt__Audience=server-dotnet-users
      - ASPNETCORE_ENVIRONMENT=Development

  db:
    image: mcr.microsoft.com/mssql/server:2022-lts
    environment:
      SA_PASSWORD: "Your_strong_password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql

volumes:
  mssql-data: